config/routes.rb
Myapp::Application.routes.draw do

  resources :transferencias
  resources :saques
  resources :depositos
  resources :contas
  resources :parcelas_emprestimos do
    collection do
      match 'tarefas', via: [:get]
      match 'pagamentos_feitos', via: [:get]
      match 'detalhes', via: [:get]
      match 'pagar', via: [:get]
    end
  end
  resources :emprestimos
  resources :autorizacao_pagamentos
  resources :enderecos_empresas
  resources :filiais_empresas
  resources :enderecos_clientes
  resources :clientes do
    collection do
      match 'campo_cliente', via: [:get]
    end
  end
  resources :formas_pagamentos
  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end
  resources :aceite_termos do
    collection do
      match 'leitura_termos', via: [:get]
      match 'aceitar_termos', via: [:get]
      match 'cadastro_pessoa', via: [:get]
    end
  end
  resources :landing do
    collection do
      match 'compra_aprovada', via: [:get, :post]
      match 'compra_recusada', via: [:get, :post]
      match 'compra_pendente', via: [:get, :post]

      match 'mercado_pago', via: [:get, :post]

      match 'observacao', via: [:get, :post]
    end 
  end
  resources :termos_usos
  resources :pessoas

  resources :permissoes_acessos
  resources :modulos
  
  resources :empresas do
    collection do
      get 'listagem'
      get 'setar'
      get 'informacoes'
      post 'adicionar_participante'
    end
  end

  devise_for :usuarios
  
  # You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'
  
  get 'dashboards/dashboard_1'

  get 'dashboards/filtrar'
  post 'dashboards/filtrar'
  post 'landing/logar'
end

app/models/aceite_termo.rb
class AceiteTermo < ApplicationRecord
  has_many :usuarios
  belongs_to :termos_uso
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base 
  self.abstract_class = true
end

app/models/conta.rb
class Conta < ApplicationRecord
  belongs_to :pessoa
  belongs_to :empresa
  has_many :depositos
  has_many :saques
  has_many :transferencias
end

app/models/deposito.rb
class Deposito < ApplicationRecord
  belongs_to :conta
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	has_many :permissoes_acessos
end

app/models/modulo.rb
class Modulo < ApplicationRecord
end

app/models/permissoes_acesso.rb
class PermissoesAcesso < ApplicationRecord
  belongs_to :usuario
  belongs_to :modulo
  belongs_to :empresa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  has_one :usuario
end

app/models/saque.rb
class Saque < ApplicationRecord
  belongs_to :conta
end

app/models/termos_uso.rb
class TermosUso < ApplicationRecord
	has_many :aceite_termos
end

app/models/transferencia.rb
class Transferencia < ApplicationRecord
  belongs_to :empresa
  belongs_to :conta
end

app/models/usuario.rb
class Usuario < ApplicationRecord
	has_one :pessoa
	belongs_to :aceite_termo
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/contas_controller.rb
class ContasController < ApplicationController
  before_action :set_conta, only: [:show, :edit, :update, :destroy]

  # GET /contas
  # GET /contas.json
  def index
    @contas = Conta.where(ativo: true, empresa_id: session[:empresa_id])
  end

  # GET /contas/1
  # GET /contas/1.json
  def show
  end

  # GET /contas/new
  def new
    @conta = Conta.new
  end

  # GET /contas/1/edit
  def edit
  end

  # POST /contas
  # POST /contas.json
  def create
    @conta = Conta.new(conta_params)
    @conta.agencia = 0001
    @conta.digito_agencia = 1
    @conta.saldo = 0
    @conta.ativo = true
    @conta.empresa_id = session[:empresa_id]

    respond_to do |format|
      @conta.numero_conta = "#{1010}#{@conta.id}".to_i
      @conta.digito_conta = 1
      if @conta.save
        format.html { redirect_to @conta, notice: 'Cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @conta }
      else
        format.html { render :new }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contas/1
  # PATCH/PUT /contas/1.json
  def update
    respond_to do |format|
      if @conta.update(conta_params)
        format.html { redirect_to @conta, notice: 'Atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @conta }
      else
        format.html { render :edit }
        format.json { render json: @conta.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contas/1
  # DELETE /contas/1.json
  def destroy
    @conta.update(ativo: false)
    respond_to do |format|
      format.html { redirect_to contas_url, notice: 'Deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conta
      @conta = Conta.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conta_params
      params.require(:conta).permit(:agencia, :digito_agencia, :numero_conta, :digito_conta, :pessoa_id, :saldo, :ativo, :empresa_id, :senha)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/depositos_helper.rb
module DepositosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/modulos_helper.rb
module ModulosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/saques_helper.rb
module SaquesHelper
end

app/helpers/termos_usos_helper.rb
module TermosUsosHelper
end

app/views/contas/_form.html.erb
<%= form_for(@conta) do |f| %>
  	<% if @conta.errors.any? %>
	    <div id="error_explanation" class="alert alert-danger" style="width: 400px;">
	      <ul>
	        <% @conta.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	        <% end %>
	      </ul>
	    </div>
  	<% end %>

  	<form class="form-horizontal">
    	<div class="row">
			<div class="field form-group col-lg-6">
				<%= f.label :pessoa_id, "Títular" %>
				<%= f.select :pessoa_id, options_for_select(Pessoa.where(:empresa_id => session[:empresa_id], :ativo => true, :usuario_id => current_usuario).collect {|e| ["#{e.nome} #{e.sobrenome}", e.id]}), { prompt: "Selecione o Títular" }, {:class => "form-control selectpicker", :style => "width: 100%", :required => true} %>
			</div>
			<div class="field form-group col-lg-6">
				<%= f.label :senha, "Senha de acesso" %>
				<%= f.password_field :senha, :class => "form-control", :required => true, autofocus: true %>
			</div>
			<br>
			<div class="col-lg-7">
			    <%= button_tag(type: 'submit', class: "btn btn-sm btn-primary", data: { disable_with: "Salvando..." }, title: 'Salvar') do %>
			        <i class="fa fa-check"> Salvar</i>
			    <% end %>&nbsp;&nbsp;&nbsp;
			    <%= link_to(contas_path, class: "btn btn-sm btn-primary", title: 'Voltar') do %>
			        <i class="fa fa-reply"> Voltar</i>
			    <% end %>&nbsp;&nbsp;&nbsp;
			    <% if params[:action] == "edit" %>
			        <%= link_to(@conta, class: "btn btn-sm btn-primary", title: 'Visualizar') do %>
			          <i class="fa fa-search"> Visualizar</i>
			        <% end %>
			    <% end %>
		  	</div>
		</div>
	</form>
<% end %>

app/views/contas/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h1>Edição de Conta</h1>
				</div>
				<div class="ibox-content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/contas/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
        <h2>Detalhes da Conta</h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
            <div class="alert alert-info">
                <p align="center" id="notice"><%= notice %></p>
            </div>
            <% end %>
        </div>
        <div class="col">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="table-responsive" style="padding-bottom: 150px;">
                        <% if @contas.collect.count == 0 %>
                            <h1 style="text-align: center; padding-top: 200px;"><%= link_to(new_conta_path, class: 'btn btn-lg btn-primary btn-outline btn-rounded') do %>
                                <i class="fa fa-plus"></i> Cadastrar Nova Conta
                            <% end %></h1>
                        <% else %>
                            <table class="table table-hover">
                                <thead class="table table-bordered">
                                    <tr>
                                        <th>Títular</th>
                                        <th>Agência</th>
                                        <th>Número Conta</th>
                                        <th>Ações</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <% @contas.each do |conta| %>
                                        <tr>
                                            <td><%= conta.pessoa.nome %> <%= conta.pessoa.sobrenome %></td>
                                            <td>000<%= conta.agencia %>-<%= conta.digito_agencia %></td>
                                            <td>00<%= conta.numero_conta %>-<%= conta.digito_conta %></td>
                                            <td>
                                                <div class="input-group-btn">
                                                    <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button">Ações <span class="caret"></span></button>
                                                    <ul class="dropdown-menu">
                                                        <li>
                                                            <%= link_to 'Editar Senha', edit_conta_path(conta), :class => 'btn btn-default', title: 'Editar'%>
                                                        </li>
                                                        <li>
                                                            <%= link_to 'Encerrar Conta', conta, id: "encerrar_conta", :class => 'btn btn-default', :title => 'Encerrar' %>

                                                        </li>
                                                    </ul>
                                                </div>
                                            </td>
                                        </tr>
                                        <script type="text/javascript">
                                            //Caso botão encerrar seja clicado apareça uma mensagem de confirmação
                                            $("#encerrar_conta").click(function(e) {
                                                e.preventDefault();
                                                Swal.fire({
                                                  title: 'Tem certeza que deseja encerrar essa conta?',
                                                  text: "Caso faça isso, não será mais possível recuperá-la.",
                                                  icon: 'warning',
                                                  position: 'center',
                                                  confirmButtonColor: '#28A745',
                                                  cancelButtonColor: '#ED5565',
                                                  showCancelButton: true,
                                                  confirmButtonText: 'Sim, encerrar.',
                                                  cancelButtonText: 'Não, voltar.',
                                                  reverseButtons: false,
                                                  width: "500px"
                                                }).then((result) => {
                                                  //Se confirmar a conta será encerrada
                                                  if (result.value) {
                                                    $.ajax({
                                                        url: '/contas/<%= conta.id %>',
                                                        method: 'DELETE'
                                                    })
                                                    .done(function(retorno) {
                                                        setTimeout(function() {
                                                            location.reload();
                                                        }, 1000);
                                                        Swal.fire({
                                                            position: 'center',
                                                            icon: 'success',
                                                            title: 'Conta encerrada com sucesso.',
                                                            timer: 1000
                                                        })
                                                    });
                                                  }
                                                  //Se não o click será cancelado
                                                  else if (
                                                    result.dismiss === Swal.DismissReason.cancel
                                                  ) {
                                                    
                                                  }
                                                })
                                            });
                                        </script>
                                    <% end %>
                                </tbody>
                            </table>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/contas/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
	    <div class="col-lg-12">
            <% if !notice.nil? %>
            <div class="alert alert-info">
                <p align="center" id="notice"><%= notice %></p>
            </div>
            <% end %>
	    </div>
	    <div class="col-lg-12">
	    	<div class="ibox float-e-margins">
	        	<div class="ibox-title">
	        		<div class="row">
		                <div class="col-lg-12 col-sm-10 col-md-10 col-xs-8">
	          				<h2 align="center">Cadastre o Conta</h2>
		            	</div>
		            </div>
	        	</div>
				<div class="ibox-content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/contas/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
        <h2>Conta de: <%= @conta.pessoa.nome %> <%= @conta.pessoa.sobrenome %>  </h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
                <div class="alert alert-info">
                    <p align="center" id="notice"><%= notice %></p>
                </div>
            <% end %>
        </div>
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox product-detail">
                    <div class="ibox-content">
                        <div class="row">
                            <h3>Informações:</h3>
                            <dl class="small m-t-md">
                                <div class="col-lg-6" style="font-size: 12px;">
                                    <dt>Agência:</dt>
                                    <dd>
                                        000<%= @conta.agencia %>-<%= @conta.digito_agencia %>    
                                    </dd>
                                    <br>
                                    <dt>Conta Corrente:</dt>
                                    <dd>
                                        00<%= @conta.numero_conta %>-<%= @conta.digito_conta %>   
                                    </dd>
                                    <br>
                                </div>
                            </dl>
                            <div class="col-lg-7">
                                <%= link_to(contas_path, class: "btn btn-sm btn-primary", title: 'Voltar') do %>
                                    <i class="fa fa-reply"> Voltar</i>
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>