config/routes.rb
Myapp::Application.routes.draw do

  resources :transferencias
  resources :saques
  resources :depositos
  resources :contas
  resources :parcelas_emprestimos do
    collection do
      match 'tarefas', via: [:get]
      match 'pagamentos_feitos', via: [:get]
      match 'detalhes', via: [:get]
      match 'pagar', via: [:get]
    end
  end
  resources :emprestimos
  resources :autorizacao_pagamentos
  resources :enderecos_empresas
  resources :filiais_empresas
  resources :enderecos_clientes
  resources :clientes do
    collection do
      match 'campo_cliente', via: [:get]
    end
  end
  resources :formas_pagamentos
  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end
  resources :aceite_termos do
    collection do
      match 'leitura_termos', via: [:get]
      match 'aceitar_termos', via: [:get]
      match 'cadastro_pessoa', via: [:get]
    end
  end
  resources :landing do
    collection do
      match 'compra_aprovada', via: [:get, :post]
      match 'compra_recusada', via: [:get, :post]
      match 'compra_pendente', via: [:get, :post]

      match 'mercado_pago', via: [:get, :post]

      match 'observacao', via: [:get, :post]
    end 
  end
  resources :termos_usos
  resources :pessoas

  resources :permissoes_acessos
  resources :modulos
  
  resources :empresas do
    collection do
      get 'listagem'
      get 'setar'
      get 'informacoes'
      post 'adicionar_participante'
    end
  end

  devise_for :usuarios
  
  # You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'
  
  get 'dashboards/dashboard_1'

  get 'dashboards/filtrar'
  post 'dashboards/filtrar'
  post 'landing/logar'
end

app/models/aceite_termo.rb
class AceiteTermo < ApplicationRecord
  has_many :usuarios
  belongs_to :termos_uso
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base 
  self.abstract_class = true
end

app/models/conta.rb
class Conta < ApplicationRecord
  belongs_to :pessoa
  belongs_to :empresa
  has_many :depositos
  has_many :saques
  has_many :transferencias
end

app/models/deposito.rb
class Deposito < ApplicationRecord
  belongs_to :conta
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	has_many :permissoes_acessos
end

app/models/modulo.rb
class Modulo < ApplicationRecord
end

app/models/permissoes_acesso.rb
class PermissoesAcesso < ApplicationRecord
  belongs_to :usuario
  belongs_to :modulo
  belongs_to :empresa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  has_one :usuario
end

app/models/saque.rb
class Saque < ApplicationRecord
  belongs_to :conta
end

app/models/termos_uso.rb
class TermosUso < ApplicationRecord
	has_many :aceite_termos
end

app/models/transferencia.rb
class Transferencia < ApplicationRecord
  belongs_to :empresa
  belongs_to :conta
end

app/models/usuario.rb
class Usuario < ApplicationRecord
	has_one :pessoa
	belongs_to :aceite_termo
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/modulos_controller.rb
class ModulosController < ApplicationController
  before_action :set_modulo, only: [:show, :edit, :update, :destroy]

  # GET /modulos
  # GET /modulos.json
  def index
    @modulos = Modulo.where(:ativo => true, :empresa_id => session[:empresa_id]).order(:descricao)
  end

  # GET /modulos/1
  # GET /modulos/1.json
  def show
  end

  # GET /modulos/new
  def new
    @modulo = Modulo.new
  end

  # GET /modulos/1/edit
  def edit
  end

  # POST /modulos
  # POST /modulos.json
  def create
    @modulo = Modulo.new(modulo_params)
    @modulo.ativo = true
    @modulo.empresa_id = session[:empresa_id]

    respond_to do |format|
      if @modulo.save
        format.html { redirect_to @modulo, notice: 'Módulo cadastrado com sucesso.' }
        format.json { render action: 'show', status: :created, location: @modulo }
      else
        format.html { render action: 'new' }
        format.json { render json: @modulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modulos/1
  # PATCH/PUT /modulos/1.json
  def update
    respond_to do |format|
      if @modulo.update(modulo_params)
        @modulo.empresa_id = session[:empresa_id]
        format.html { redirect_to @modulo, notice: 'Módulo atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @modulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modulos/1
  # DELETE /modulos/1.json
  def destroy
    @modulo.update(ativo: :false)
    respond_to do |format|
      format.html { redirect_to modulos_url, notice: 'Módulo deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modulo
      @modulo = Modulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modulo_params
      params.require(:modulo).permit(:descricao, :ativo, :empresa_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/depositos_helper.rb
module DepositosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/modulos_helper.rb
module ModulosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/saques_helper.rb
module SaquesHelper
end

app/helpers/termos_usos_helper.rb
module TermosUsosHelper
end

app/views/modulos/_form.html.erb
<%= form_for(@modulo) do |f| %>
  <% if @modulo.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" style="width: 400px;">
      <ul>
      <% @modulo.errors.full_messages.each do |message| %>
        <li><%= message %>.</li><br>
      <% end %>
      </ul>
    </div>
  <% end %>
    <form class="form-horizontal">
        <div class="row">
            <div class="field form-group col-lg-6">
              <%= f.label :descricao, "Descrição" %> <e style="color:red">*</e>
              <%= f.text_field :descricao, class: 'form-control', required: true, autofocus: true %>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <%= button_tag(type: 'submit', class: "btn btn-primary", title: 'Salvar') do %>
                    <i class="fa fa-save"></i> Salvar
                <% end %>   
            </div>
        </div>
    </form>
<% end %>

app/views/modulos/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h1>Edição de Módulo</h1>
				</div>
				<div class="ibox-content">
					<%= render 'form' %>
					<%= link_to '', @modulo, class: 'btn btn-sm btn-warning fa fa-search', title: 'Visualizar' %> 
					<%= link_to '', modulos_path, class: 'btn btn-sm btn-danger fa fa-reply', title: 'Voltar' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/modulos/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
        <h2>Módulos</h2>
    </div>
    <div class="col-lg-1 col-lg-push-1 col-md-1 col-md-push-1 col-sm-1 col-sm-push-1 col-xs-2 col-xs-pull-1">
        <h2><%= link_to(new_modulo_path, class: 'btn btn-primary btn-outline btn-rounded') do %>
            <i class="fa fa-plus"></i> Novo
        <% end %></h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
                <div class="alert alert-info">
                    <p align="center"><%= notice %></p>
                </div>
            <% end %>
        </div>
        <div class="col">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="table-responsive" style="padding-bottom: 80px;">
                        <table class="table table-hover">
                            <thead class="table table-bordered">
                                <tr>
                                    <th>Descrição</th>
                                    <th colspan="3"></th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @modulos.each do |modulo| %>
                                <tr>
                                    <td><%= modulo.descricao %></td>
                                    <div>
                                        <td>
                                            <%= link_to '', modulo, class: 'fa fa-search fa-sm btn btn-primary btn-rounded', title: 'Visualizar' %>
                                        </td>
                                        <td>
                                            <%= link_to '', edit_modulo_path(modulo), class: 'fa fa-pencil-square-o fa-sm btn btn-warning btn-outline btn-rounded', title: 'Editar'%>
                                        </td>
                                        <td>
                                            <%= link_to 'Deletar', modulo, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse registro ?' }, :class => 'btn btn-default', :title => 'Deletar' %>
                                        </td>
                                    </div>
                                  </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/modulos/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
	    <div class="col-lg-12">
	        <% if !notice.nil? %>
	            <div class="alert alert-info">
	                <p align="center"><%= notice %></p>
	            </div>
	        <% end %>
	    </div>
	    <div class="col-lg-12">
	    	<div class="ibox float-e-margins">
	        	<div class="ibox-title">
	        		<div class="row">
		                <div class="col-lg-12 col-sm-10 col-md-10 col-xs-8">
	          				<h2 align="center">Cadastre o Módulo</h2>
		            	</div>
		            </div>
	        	</div>
				<div class="ibox-content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/modulos/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
        <h2><%= @modulo.descricao %></h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
                <div class="alert alert-info">
                    <p align="center"><%= notice %></p>
                </div>
            <% end %>
        </div>
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox product-detail">
                    <div class="ibox-content">
                        <div class="row">
                            <h3>Informações:</h3>
                            <dl class="small m-t-md">
                                <div class="col-lg-6" style="font-size: 12px;">  
                                    <dt>Data de Cadastro:</dt>
                                    <dd><%= @modulo.created_at.strftime("%d/%m/%Y") %></dd><br> 
                                </div>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>