config/routes.rb
Myapp::Application.routes.draw do

  resources :transferencias
  resources :saques
  resources :depositos
  resources :contas
  resources :parcelas_emprestimos do
    collection do
      match 'tarefas', via: [:get]
      match 'pagamentos_feitos', via: [:get]
      match 'detalhes', via: [:get]
      match 'pagar', via: [:get]
    end
  end
  resources :emprestimos
  resources :autorizacao_pagamentos
  resources :enderecos_empresas
  resources :filiais_empresas
  resources :enderecos_clientes
  resources :clientes do
    collection do
      match 'campo_cliente', via: [:get]
    end
  end
  resources :formas_pagamentos
  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end
  resources :aceite_termos do
    collection do
      match 'leitura_termos', via: [:get]
      match 'aceitar_termos', via: [:get]
      match 'cadastro_pessoa', via: [:get]
    end
  end
  resources :landing do
    collection do
      match 'compra_aprovada', via: [:get, :post]
      match 'compra_recusada', via: [:get, :post]
      match 'compra_pendente', via: [:get, :post]

      match 'mercado_pago', via: [:get, :post]

      match 'observacao', via: [:get, :post]
    end 
  end
  resources :termos_usos
  resources :pessoas

  resources :permissoes_acessos
  resources :modulos
  
  resources :empresas do
    collection do
      get 'listagem'
      get 'setar'
      get 'informacoes'
      post 'adicionar_participante'
    end
  end

  devise_for :usuarios
  
  # You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'
  
  get 'dashboards/dashboard_1'

  get 'dashboards/filtrar'
  post 'dashboards/filtrar'
  post 'landing/logar'
end

app/models/aceite_termo.rb
class AceiteTermo < ApplicationRecord
  has_many :usuarios
  belongs_to :termos_uso
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base 
  self.abstract_class = true
end

app/models/conta.rb
class Conta < ApplicationRecord
  belongs_to :pessoa
  belongs_to :empresa
  has_many :depositos
  has_many :saques
  has_many :transferencias
end

app/models/deposito.rb
class Deposito < ApplicationRecord
  belongs_to :conta
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	has_many :permissoes_acessos
end

app/models/modulo.rb
class Modulo < ApplicationRecord
end

app/models/permissoes_acesso.rb
class PermissoesAcesso < ApplicationRecord
  belongs_to :usuario
  belongs_to :modulo
  belongs_to :empresa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  has_one :usuario
end

app/models/saque.rb
class Saque < ApplicationRecord
  belongs_to :conta
end

app/models/termos_uso.rb
class TermosUso < ApplicationRecord
	has_many :aceite_termos
end

app/models/transferencia.rb
class Transferencia < ApplicationRecord
  belongs_to :empresa
  belongs_to :conta
end

app/models/usuario.rb
class Usuario < ApplicationRecord
	has_one :pessoa
	belongs_to :aceite_termo
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/saques_controller.rb
class SaquesController < ApplicationController
  before_action :set_saque, only: [:show, :edit, :update, :destroy]

  # GET /saques
  # GET /saques.json
  def index
    @saques = Saque.joins(:conta).where("contas.pessoa_id = ?", session[:pessoa]).where(ativo: true, empresa_id: session[:empresa_id])
  end

  # GET /saques/1
  # GET /saques/1.json
  def show
  end

  # GET /saques/new
  def new
    @saque = Saque.new
    @saldo_conta = Conta.where(ativo: true, empresa_id: session[:empresa_id]).first.saldo
  end

  # GET /saques/1/edit
  def edit
  end

  # POST /saques
  # POST /saques.json
  def create
    @saque = Saque.new(saque_params)
    @saque.ativo = true
    @saque.empresa_id = session[:empresa_id]
    senha_digitada = params[:senha]

    depositos = Deposito.where(ativo: true, empresa_id: session[:empresa_id]).sum(:valor_deposito)
    transferencias = Transferencia.where(ativo: true, empresa_id: session[:empresa_id]).sum(:valor_transferencia)
    transferencias_totais = Transferencia.where(ativo: true, empresa_id: session[:empresa_id]).sum(:taxa_transferencia)
    saques = Saque.where(ativo: true, empresa_id: session[:empresa_id]).sum(:valor_saque)
    saldo = depositos - transferencias - saques - transferencias_totais

    if ((saldo - @saque.valor_saque).to_f > 0)
      calculo_saldo = true
    end

    if (senha_digitada == @saque.conta.senha && saldo != 0 && calculo_saldo == true)
      @liberacao = true
      if @saque.save
        @id_conta = @saque.id
      end
    else
      @liberacao = false
    end
    
    render :new
  end

  # PATCH/PUT /saques/1
  # PATCH/PUT /saques/1.json
  def update
    respond_to do |format|
      if @saque.update(saque_params)
        format.html { redirect_to @saque, notice: 'Atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @saque }
      else
        format.html { render :edit }
        format.json { render json: @saque.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saques/1
  # DELETE /saques/1.json
  def destroy
    @saque.update(ativo: false)
    respond_to do |format|
      format.html { redirect_to saques_url, notice: 'Deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saque
      @saque = Saque.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def saque_params
      params.require(:saque).permit(:conta_id, :valor_saque, :empresa_id, :ativo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/depositos_helper.rb
module DepositosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/modulos_helper.rb
module ModulosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/saques_helper.rb
module SaquesHelper
end

app/helpers/termos_usos_helper.rb
module TermosUsosHelper
end

app/views/saques/_form.html.erb
<%= form_for(@saque) do |f| %>
  	<% if @saque.errors.any? %>
	    <div id="error_explanation" class="alert alert-danger" style="width: 400px;">
	      <ul>
	        <% @saque.errors.full_messages.each do |message| %>
	          <li><%= message %></li>
	        <% end %>
	      </ul>
	    </div>
  	<% end %>

  	<form class="form-horizontal">
    	<div class="row">
			<div class="field form-group col-lg-12">
				<%= f.label :conta_id, "Conta de Saque" %>
				<%= f.select :conta_id, options_for_select(Conta.where(:empresa_id => session[:empresa_id], :ativo => true).collect {|e| ["#{e.pessoa.nome} #{e.pessoa.sobrenome} - 000#{e.agencia}-#{e.digito_agencia}, 00#{e.numero_conta}-#{e.digito_conta}", e.id]}), { prompt: "Selecione o Conta" }, {:class => "form-control selectpicker", :style => "width: 100%", :required => true} %>
			</div>
			<% if params[:action] == "new" %>
				<div class="field form-group col-lg-12 ">
				    <%= f.label :valor_saque, 'Valor Saque'%> <e style="color:red;">*</e>
				    <%= f.number_field :valor_saque, value: number_to_currency(f.object.valor_saque.to_f, delimiter: ',', unit: 'R$'), :step => 0.001, :class => 'form-control moeda', :required => true %>
				</div>
			<% else %>
				  <div class="field form-group col-lg-12 ">
				    <%= f.label :valor_saque, 'Valor Saque'%> <e style="color:red;">*</e>
				    <%= f.text_field :valor_saque, :class => 'form-control moeda', :required => true %>
				  </div>
			<% end %>
			<div class="field form-group col-lg-12">
				<%= label_tag :senha, "Senha de acesso" %>
				<%= password_field_tag :senha, nil, :class => "form-control", :required => true, autofocus: true %>
			</div>
			<br>
			<div class="col-lg-7">
			    <%= button_tag(type: 'submit', class: "btn btn-sm btn-primary", data: { disable_with: "Contagem de Notas..." }, title: 'Confirmar', id: "botao_saque") do %>
			        <i class="fa fa-check"> Confirmar</i>
			    <% end %>&nbsp;&nbsp;&nbsp;
			    <%= link_to(saques_path, class: "btn btn-sm btn-primary", title: 'Voltar') do %>
			        <i class="fa fa-reply"> Voltar</i>
			    <% end %>&nbsp;&nbsp;&nbsp;
			    <% if params[:action] == "edit" %>
			        <%= link_to(@saque, class: "btn btn-sm btn-primary", title: 'Visualizar') do %>
			          <i class="fa fa-search"> Visualizar</i>
			        <% end %>
			    <% end %>
		  	</div>
		</div>
	</form>
<% end %>

<script type="text/javascript">
  	$(document).ready(function() {
		var mask = {
		    money: function() {
		      var el = this
		      ,exec = function(v) {
		        v = v.replace(/\D/g,"");
		        v = new String(Number(v));
		        var len = v.length;
		        if (1== len)
		        v = v.replace(/(\d)/,"0.0$1");
		        else if (2 == len)
		        v = v.replace(/(\d)/,"0.$1");
		        else if (len > 2) {
		        v = v.replace(/(\d{2})$/,'.$1');
		        }
		        return v;
		      };
		      setTimeout(function(){
		      el.value = exec(el.value);
		      },1);
		    }
	  	}

		$(function(){
			$('.moeda').bind('keypress',mask.money)
		});
  	});
</script>

app/views/saques/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h1>Edição de Saque</h1>
				</div>
				<div class="ibox-content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/saques/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
        <h2>Saques</h2>
    </div>
    <div class="col-lg-1 col-lg-push-1 col-md-1 col-md-push-1 col-sm-1 col-sm-push-1 col-xs-2 col-xs-pull-1">
        <h2><%= link_to(new_saque_path, class: 'btn btn-primary btn-outline btn-rounded') do %>
            <i class="fa fa-plus"></i> Novo
        <% end %></h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
            <div class="alert alert-info">
                <p align="center" id="notice"><%= notice %></p>
            </div>
            <% end %>
        </div>
        <div class="col">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="table-responsive" style="padding-bottom: 80px;">
                        <table class="table table-hover">
                            <thead class="table table-bordered">
                                <tr>
                                    <th>Conta</th>
                                    <th>Valor Saque</th>
                                    <th>Data Saque</th>
                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @saques.each do |saque| %>
                                    <tr>
                                        <td><%= saque.conta.pessoa.nome %> <%= saque.conta.pessoa.sobrenome %>, <%= saque.conta.agencia %>-<%= saque.conta.digito_agencia %>, <%= saque.conta.numero_conta %>-<%= saque.conta.digito_conta %></td>
                                        <td><%= number_to_currency(saque.valor_saque) %></td>
                                        <td><%= l(saque.created_at) %></td>
                                        <td>
                                            <div class="input-group-btn">
                                                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button">Ações <span class="caret"></span></button>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <%= link_to 'Ver', saque, :class => 'btn btn-default', :title => 'Visualizar' %>
                                                    </li>
                                                    <li>
                                                        <%= link_to 'Editar', edit_saque_path(saque), :class => 'btn btn-default', title: 'Editar'%>
                                                    </li>
                                                    <li>
                                                        <%= link_to 'Deletar', saque, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse registro ?' }, :class => 'btn btn-default', :title => 'Deletar' %>
                                                    </li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/saques/new.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
	    <div class="col-lg-12">
            <% if !notice.nil? %>
            <div class="alert alert-info">
                <p align="center" id="notice"><%= notice %></p>
            </div>
            <% end %>
	    </div>
	    <div class="col-lg-12">
	    	<div class="ibox float-e-margins">
	        	<div class="ibox-title">
	        		<div class="row">
		                <div class="col-lg-12 col-sm-10 col-md-10 col-xs-8">
	          				<h2 align="center">Realizar Saque</h2>
		            	</div>
		            </div>
	        	</div>
				<div class="ibox-content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(e) {
		if (<%= @liberacao %> == false){
			Swal.fire({
			  title: 'Operação não autorizada pela instituição',
			  html: 'Tente novamente.',
			  timer: 3000,
			  timerProgressBar: true,
		      icon: 'error',
		      position: 'center',
		      width: "500px",
		      showConfirmButton: false
			})
		}
		else {
			Swal.fire({
			  title: 'Aguarde a contagem de notas...',
			  html: 'Em segundos o valor será liberado.',
			  timer: 3000,
			  timerProgressBar: true,
	          icon: 'success',
	          position: 'center',
	          width: "500px"
			})
			setTimeout(function() {
                window.location.replace("saques/<%= @id_conta %>");
            }, 3000);
		}
	});
</script>

app/views/saques/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
        <h2>Detalhes do Saque</h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
                <div class="alert alert-info">
                    <p align="center" id="notice"><%= notice %></p>
                </div>
            <% end %>
        </div>
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox product-detail">
                    <div class="ibox-content">
                        <div class="row">
                            <h3>Informações:</h3>
                            <dl class="small m-t-md">
                                <div class="col-lg-6" style="font-size: 12px;">
                                    <dt>Conta:</dt>
                                    <dd>
                                        <%= @saque.conta.pessoa.nome %> <%= @saque.conta.pessoa.sobrenome %>, Agência: 000<%= @saque.conta.agencia %>-<%= @saque.conta.digito_agencia %>, Conta Corrente: 00<%= @saque.conta.numero_conta %>-<%= @saque.conta.digito_conta %>  
                                    </dd>
                                    <br>
                                    <dt>Valor Saque:</dt>
                                    <dd>
                                        <%= number_to_currency(@saque.valor_saque) %>   
                                    </dd>
                                    <br>
                                    <dt>Data Saque:</dt>
                                    <dd>
                                        <%= l(@saque.created_at) %>   
                                    </dd>
                                    <br>
                                </div>
                            </dl>
                            <div class="col-lg-7">
                                <%= link_to(saques_path, class: "btn btn-sm btn-primary", title: 'Voltar') do %>
                                    <i class="fa fa-reply"> Voltar</i>
                                <% end %>&nbsp;&nbsp;&nbsp;
                                <%= link_to(new_saque_path, class: 'btn btn-sm btn-primary') do %>
                                    <i class="fa fa-plus"></i> Novo
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>