config/routes.rb
Myapp::Application.routes.draw do

  resources :transferencias
  resources :saques
  resources :depositos
  resources :contas
  resources :parcelas_emprestimos do
    collection do
      match 'tarefas', via: [:get]
      match 'pagamentos_feitos', via: [:get]
      match 'detalhes', via: [:get]
      match 'pagar', via: [:get]
    end
  end
  resources :emprestimos
  resources :autorizacao_pagamentos
  resources :enderecos_empresas
  resources :filiais_empresas
  resources :enderecos_clientes
  resources :clientes do
    collection do
      match 'campo_cliente', via: [:get]
    end
  end
  resources :formas_pagamentos
  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end
  resources :aceite_termos do
    collection do
      match 'leitura_termos', via: [:get]
      match 'aceitar_termos', via: [:get]
      match 'cadastro_pessoa', via: [:get]
    end
  end
  resources :landing do
    collection do
      match 'compra_aprovada', via: [:get, :post]
      match 'compra_recusada', via: [:get, :post]
      match 'compra_pendente', via: [:get, :post]

      match 'mercado_pago', via: [:get, :post]

      match 'observacao', via: [:get, :post]
    end 
  end
  resources :termos_usos
  resources :pessoas

  resources :permissoes_acessos
  resources :modulos
  
  resources :empresas do
    collection do
      get 'listagem'
      get 'setar'
      get 'informacoes'
      post 'adicionar_participante'
    end
  end

  devise_for :usuarios
  
  # You can have the root of your site routed with "root"
  root to: 'dashboards#dashboard_1'
  
  get 'dashboards/dashboard_1'

  get 'dashboards/filtrar'
  post 'dashboards/filtrar'
  post 'landing/logar'
end

app/models/aceite_termo.rb
class AceiteTermo < ApplicationRecord
  has_many :usuarios
  belongs_to :termos_uso
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base 
  self.abstract_class = true
end

app/models/conta.rb
class Conta < ApplicationRecord
  belongs_to :pessoa
  belongs_to :empresa
  has_many :depositos
  has_many :saques
  has_many :transferencias
end

app/models/deposito.rb
class Deposito < ApplicationRecord
  belongs_to :conta
end

app/models/empresa.rb
class Empresa < ApplicationRecord
	has_many :permissoes_acessos
end

app/models/modulo.rb
class Modulo < ApplicationRecord
end

app/models/permissoes_acesso.rb
class PermissoesAcesso < ApplicationRecord
  belongs_to :usuario
  belongs_to :modulo
  belongs_to :empresa
end

app/models/pessoa.rb
class Pessoa < ApplicationRecord
  has_one :usuario
end

app/models/saque.rb
class Saque < ApplicationRecord
  belongs_to :conta
end

app/models/termos_uso.rb
class TermosUso < ApplicationRecord
	has_many :aceite_termos
end

app/models/transferencia.rb
class Transferencia < ApplicationRecord
  belongs_to :empresa
  belongs_to :conta
end

app/models/usuario.rb
class Usuario < ApplicationRecord
	has_one :pessoa
	belongs_to :aceite_termo
	devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/pessoas_controller.rb
class PessoasController < ApplicationController
  before_action :set_pessoa, only: [:show, :edit, :update, :destroy]

  # GET /pessoas
  # GET /pessoas.json
  def index
    @pessoas = Pessoa.where(:ativo => true, :empresa_id => session[:empresa_id]).order(:nome)
  end

  # GET /pessoas/1
  # GET /pessoas/1.json
  def show
  end

  # GET /pessoas/new
  def new
    @pessoa = Pessoa.new
  end

  # GET /pessoas/1/edit
  def edit
  end

  # POST /pessoas
  # POST /pessoas.json
  def create
    @pessoa = Pessoa.new(pessoa_params)
    session[:empresa_id] = 1
    @pessoa.usuario_id = current_usuario.id
    @pessoa.cpf = params[:pessoa][:cpf].gsub(".", "").gsub("-", "")
    @pessoa.cep = params[:pessoa][:cep].gsub("-", "")
    @pessoa.empresa_id = session[:empresa_id]
    @pessoa.ativo = true

    respond_to do |format|
      if @pessoa.save
        format.html { redirect_to root_path, notice: 'Cadastro realizado com sucesso.' }
      else
        format.html { render action: 'new' }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pessoas/1
  # PATCH/PUT /pessoas/1.json
  def update
    respond_to do |format|
      if @pessoa.update(pessoa_params)
        format.html { redirect_to @pessoa, notice: 'Cadastro atualizado com sucesso.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pessoa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pessoas/1
  # DELETE /pessoas/1.json
  def destroy
    @pessoa.update(ativo: false)
    respond_to do |format|
      format.html { redirect_to pessoas_url, notice: 'Cadastro deletado com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pessoa
      @pessoa = Pessoa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pessoa_params
      params.require(:pessoa).permit(:tipo_pessoa, :nome, :sobrenome, :data_nascimento, :genero, :usuario_id, :ativo, :empresa_id, :telefone, :rua, :cidade, :bairro, :numero, :complemento, :estado, :cpf, :rg)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def is_active_controller(controller_name)
        params[:controller] == controller_name ? "active" : nil
    end

    def is_active_action(action_name)
        params[:action] == action_name ? "active" : nil
    end
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/contas_helper.rb
module ContasHelper
end

app/helpers/depositos_helper.rb
module DepositosHelper
end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/modulos_helper.rb
module ModulosHelper
end

app/helpers/pessoas_helper.rb
module PessoasHelper
end

app/helpers/saques_helper.rb
module SaquesHelper
end

app/helpers/termos_usos_helper.rb
module TermosUsosHelper
end

app/views/pessoas/_form.html.erb
<%= form_for(@pessoa, :usuario_id => current_usuario.id) do |f| %>
	<% if @pessoa.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" style="width: 400px;">
      <ul>
        <% @pessoa.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
	<% end %>

	<form class="form-horizontal">
	<div class="row">
		<div class="field form-group col-lg-6">
			<%= f.label :tipo_pessoa, "Tipo Pessoa" %>
			<%= f.select :tipo_pessoa, options_for_select(["Cliente", "Colaborador"]), { prompt: "Selecione o Tipo" }, {class: "form-control selectpicker", "data-live-search" =>"true", :style => "width: 100%", :required => true} %>
		</div>
		<div class="field form-group col-lg-6">
			<%= f.label :nome, "Nome" %>
			<%= f.text_field :nome, :class => "form-control", :required => true, autofocus: true %>
		</div>
		<div class="field form-group col-lg-6">
			<%= f.label :sobrenome, "Sobrenome" %>
			<%= f.text_field :sobrenome, :class => "form-control", :required => true, autofocus: true %>
		</div>
		<div class="field form-group col-lg-6">
			<%= f.label :data_nascimento, "Data de Nascimento" %>
			<%= f.text_field :data_nascimento, type: 'date', :class => "form-control", :required => true, autofocus: true %>
		</div>
		<div class="field form-group col-lg-6">
			<%= f.label :genero, "Gênero" %>
			<%= f.select :genero, options_for_select(["Masculino", "Feminino", "Outros"]), { prompt: "Selecione o Gênero" }, {class: "form-control selectpicker", "data-live-search" =>"true", :style => "width: 100%", :required => true} %>
		</div>
		<div class="field form-group col-lg-6">
			<%= f.label :cpf, "CPF" %>
			<%= f.text_field :cpf, :class => "form-control", :required => true, autofocus: true, id: 'cpf' %>
		</div>
		<div class="field form-group col-lg-6">
			<%= f.label :rg, "RG" %>
			<%= f.text_field :rg, :class => "form-control", :required => true, autofocus: true %>
		</div>
		<div>
		    <%= button_tag(type: 'submit', class: "btn btn-primary btn-rounded btn-block", data: { disable_with: "Salvando..." }, title: 'Salvar') do %>
		        <i class="fa fa-check"> Salvar</i>
		    <% end %>
	  	</div>
	</div>
</form>
<% end %>

app/views/pessoas/edit.html.erb
<div class="wrapper wrapper-content animated fadeInRight">
	<div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
			<div class="ibox float-e-margins">
				<div class="ibox-title">
					<h1>Edição de Pessoa</h1>
				</div>
				<div class="ibox-content">
					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pessoas/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-9">
        <h2>Pessoas</h2>
    </div>
    <div class="col-lg-1 col-lg-push-1 col-md-1 col-md-push-1 col-sm-1 col-sm-push-1 col-xs-2 col-xs-pull-1">
        <h2><%= link_to(new_pessoa_path, class: 'btn btn-primary btn-outline btn-rounded') do %>
            <i class="fa fa-plus"></i> Novo
        <% end %></h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
                <div class="alert alert-info">
                    <p align="center" id="notice"><%= notice %></p>
                </div>
            <% end %>
        </div>
        <div class="col">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="table-responsive" style="padding-bottom: 150px;">
                        <table class="table table-hover">
                            <thead class="table table-bordered">
                                <tr>
                                    <th>Nome Completo</th>

                                    <th>Data Nascimento</th>

                                    <th>Gênero</th>

                                    <th>CPF</th>

                                    <th>RG</th>

                                    <th>Ações</th>
                                </tr>
                            </thead>
                            <tbody>
                                <% @pessoas.each do |pessoa| %>
                                    <tr>
                                        <td><%= pessoa.nome %> <%= pessoa.sobrenome %></td>
                                        <td><%= l(pessoa.data_nascimento) %></td>
                                        <td><%= pessoa.genero %></td>
                                        <td><%= pessoa.cpf %></td>
                                        <td><%= pessoa.rg %></td>
                                        <td>
                                            <div class="input-group-btn">
                                                <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button">Ações <span class="caret"></span></button>
                                                <ul class="dropdown-menu">
                                                    <li>
                                                        <%= link_to 'Ver', pessoa, :class => 'btn btn-default', :title => 'Visualizar' %>
                                                    </li>
                                                    <li>
                                                        <%= link_to 'Editar', edit_pessoa_path(pessoa), :class => 'btn btn-default', title: 'Editar'%>
                                                    </li>
                                                    <li>
                                                        <%= link_to 'Deletar', pessoa, method: :delete, data: { confirm: 'Tem certeza que deseja excluir esse registro ?' }, :class => 'btn btn-default', :title => 'Deletar' %>
                                                    </li>
                                                </ul>
                                            </div>
                                        </td>
                                    </tr>
                                <% end %>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/pessoas/new.html.erb
<%= javascript_include_tag "forms" if ::Rails.application.assets.find_asset("uielements.js") %>
<%= stylesheet_link_tag "forms" if ::Rails.application.assets.find_asset("uielements.css") %>

<script type="text/javascript">
  $(document).ready(function() {
	//Mascara de CEP
    $('#cep').mask('99999-999');
    $("#cpf").mask("999.999.999-99");

    function limpa_formulário_cep() {
      // Limpa valores do formulário de cep.
      $("#rua").val("");
      $("#bairro").val("");
      $("#cidade").val("");
      $("#estado").val("");
    }
    //Quando o campo cep perde o foco.
    $("#cep").blur(function() {
      //Nova variável "cep" somente com dígitos.
      var cep = $(this).val().replace(/\D/g, '');
      //Verifica se campo cep possui valor informado.
      if (cep != "") {
        //Expressão regular para validar o CEP.
        var validacep = /^[0-9]{8}$/;
        //Valida o formato do CEP.
        if(validacep.test(cep)) {
          //Preenche os campos com "..." enquanto consulta webservice.
          $("#rua").val("Carregando...");
          $("#bairro").val("Carregando...");      
          $("#cidade").val("Carregando...");
          $("#estado").val("Carregando...");

          //Consulta o webservice viacep.com.br/
          $.getJSON("//viacep.com.br/ws/"+ cep +"/json/?callback=?", function(dados) {
            if (!("erro" in dados)) {
              //Atualiza os campos com os valores da consulta.
              $("#rua").val(dados.logradouro);
              $("#bairro").val(dados.bairro);
              $("#cidade").val(dados.localidade);
              $("#estado").val(dados.uf);
            } //end if.
            else {
              //CEP pesquisado não foi encontrado.
              limpa_formulário_cep();
              alert("CEP não encontrado.");
            }
          });
        } //end if.
        else {
          //cep é inválido.
          limpa_formulário_cep();
          alert("Formato de CEP inválido.");
        }
      } //end if.
      else {
        //cep sem valor, limpa formulário.
        limpa_formulário_cep();
      }
    });    
  });
</script>

<div class="row center">
    <div class="col-lg-12">
      	<div class="ibox">
	        <div class="ibox-content">
	          	<div class="scroll_content">
		            <br><br><br>
		            <% if !notice.nil? %>
		              <div class="alert alert-info">
		                <p align="center" id="notice"><%= notice %></p>
		              </div>
		            <% end %>
		            <div id="termos_de_uso">
		              	<%= form_for(@pessoa, html: {:id => "identificador_formulario"} ) do |f| %>
						  	<% if @pessoa.errors.any? %>
							    <div id="error_explanation" class="alert alert-danger" style="width: 400px;">
							      <ul>
							        <% @pessoa.errors.full_messages.each do |message| %>
							          <li><%= message %></li>
							        <% end %>
							      </ul>
							    </div>
						  	<% end %>

						  	<form class="form-horizontal">
						    	<div class="row">
									<div class="field form-group col-lg-6">
										<%= f.label :nome, "Nome" %>
										<%= f.text_field :nome, :class => "form-control", :required => true, autofocus: true %>
									</div>
									<div class="field form-group col-lg-6">
										<%= f.label :sobrenome, "Sobrenome" %>
										<%= f.text_field :sobrenome, :class => "form-control", :required => true, autofocus: true %>
									</div>
									<div class="field form-group col-lg-6">
										<%= f.label :data_nascimento, "Data de Nascimento" %>
										<%= f.text_field :data_nascimento, type: 'date', :class => "form-control", :required => true, autofocus: true %>
									</div>
									<div class="field form-group col-lg-6">
										<%= f.label :genero, "Gênero" %>
										<%= f.select :genero, options_for_select(["Masculino", "Feminino", "Outros"]), { prompt: "Selecione o Gênero" }, {class: "form-control selectpicker", "data-live-search" =>"true", :style => "width: 100%", :required => true} %>
									</div>
									<div class="field form-group col-lg-6">
										<%= f.label :cpf, "CPF" %> <e style="color:red;">*</e>
										<%= f.text_field :cpf, :class => "form-control", :required => true, autofocus: true, id: 'cpf' %>
									</div>
									<div class="field form-group col-lg-6">
										<%= f.label :rg, "RG" %>
										<%= f.text_field :rg, :class => "form-control", autofocus: true %>
									</div>

									<div class="field form-group col-lg-3">
										<%= f.label :telefone, "Telefone" %> <e style="color:red;">*</e>
										<%= f.text_field :telefone, :class => "form-control", :required => true, autofocus: true, :id => 'telefone' %>
									</div>

									<div class="field form-group col-lg-3">
										<%= f.label :cep, 'CEP' %> <e style="color:red;">*</e> <a href="http://www.buscacep.correios.com.br/sistemas/buscacep/BuscaCep.cfm" target="_framename">Buscar CEP</a>
									    <%= f.text_field :cep, :class => "form-control", :required => true, autofocus: true, :id => 'cep' %>
									</div>

									<div class="field form-group col-lg-5">
										<%= f.label :rua, 'Rua' %> <e style="color:red;">*</e>
									    <%= f.text_field :rua, :class => "form-control", :required => true, autofocus: true, :id => 'rua' %>
									</div>

									<div class="field form-group col-lg-3">
										<%= f.label :numero, 'Número do Imóvel' %> <e style="color:red;">*</e>
									    <%= f.text_field :numero, :class => "form-control", :required => true, autofocus: true, :id => 'numero' %>
									</div>

									<div class="field form-group col-lg-3">
										<%= f.label :bairro, "Bairro" %> <e style="color:red;">*</e>
										<%= f.text_field :bairro, :class => "form-control", :required => true, autofocus: true, :id => 'bairro' %>
									</div>

									<div class="field form-group col-lg-3">
										<%= f.label :estado, "Estado" %> <e style="color:red;">*</e>
										<%= f.text_field :estado, :class => "form-control", :required => true, autofocus: true, :id => 'estado' %>
									</div>

									<div class="field form-group col-lg-3">
										<%= f.label :cidade, "Cidade" %> <e style="color:red;">*</e>
										<%= f.text_field :cidade, :class => "form-control", :required => true, autofocus: true, :id => 'cidade' %>
									</div>

									<div class="field form-group col-lg-3">
										<%= f.label :complemento, "Complemento" %>
										<%= f.text_field :complemento, :class => "form-control", autofocus: true, :id => 'complemento' %>
									</div>

									<div>
									    <%= button_tag(type: 'submit', class: "btn btn-primary btn-rounded btn-block", data: { disable_with: "Salvando..." }, title: 'Salvar') do %>
									        <i class="fa fa-check"> Salvar</i>
									    <% end %>
								  	</div>
								</div>
							</form>
						<% end %>
		            </div>
	          	</div>
	        </div>
     	</div>
    </div>
</div>

<style type="text/css">
  .center {
    margin: auto;
    width: auto;
    top: auto;
    transform: translateY(-2%);
    position: auto;
  }
</style>

<script type="text/javascript">
  $(function() {
    $('.scroll_content').slimscroll({
      height: '570'
    })
  });
</script>

app/views/pessoas/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading" style="margin-top: 5px;">
    <div class="col-lg-10 col-md-10 col-sm-10 col-xs-10">
        <h2><%= @pessoa.nome %> <%= @pessoa.sobrenome %></h2>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <% if !notice.nil? %>
                <div class="alert alert-info">
                    <p align="center" id="notice"><%= notice %></p>
                </div>
            <% end %>
        </div>
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox product-detail">
                    <div class="ibox-content">
                        <div class="row">
                            <h3>Informações:</h3>
                            <dl class="small m-t-md">
                                <div class="col-lg-6" style="font-size: 12px;">  
                                    <dt>Tipo Pessoa:</dt>
                                    <dd>
                                        <%= @pessoa.tipo_pessoa %>    
                                    </dd>
                                    <br> 
                                    <dt>Data nascimento:</dt>
                                    <dd>
                                        <%= l(@pessoa.data_nascimento) %>        
                                    </dd>
                                    <br> 
                                    <dt>Gênero:</dt>
                                    <dd>
                                        <%= @pessoa.genero %>    
                                    </dd>
                                    <br> 
                                    <dt>CPF:</dt>
                                    <dd>
                                        <%= @pessoa.cpf %>     
                                    </dd>
                                    <br> 
                                    <dt>RG:</dt>
                                    <dd>
                                        <%= @pessoa.rg %>        
                                    </dd>
                                    
                                    <br> 
                                </div>
                            </dl>
                            <div class="col-lg-7">
                                <%= link_to(pessoas_path, class: "btn btn-sm btn-primary", title: 'Voltar') do %>
                                    <i class="fa fa-reply"> Voltar</i>
                                <% end %>&nbsp;&nbsp;&nbsp;
                                <%= link_to(new_pessoa_path, class: 'btn btn-sm btn-primary') do %>
                                    <i class="fa fa-plus"></i> Novo
                                <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>